export const KEYBOARD_DATA = {
  TOP: [
    { which: 81, value: 'q' },
    { which: 87, value: 'w' },
    {
      which: 69,
      value: 'e',
      vn: [
        { which: undefined, value: 'è' },
        { which: undefined, value: 'é' },
        { which: undefined, value: 'ẻ' },
        { which: undefined, value: 'ẽ' },
        { which: undefined, value: 'ẹ' },
        { which: undefined, value: 'ê' },
        { which: undefined, value: 'ề' },
        { which: undefined, value: 'ế' },
        { which: undefined, value: 'ể' },
        { which: undefined, value: 'ễ' },
        { which: undefined, value: 'ệ' },
      ],
    },
    { which: 65, value: 'r' },
    { which: 84, value: 't' },
    {
      which: 89,
      value: 'y',
      vn: [
        { which: undefined, value: 'ỳ' },
        { which: undefined, value: 'ý' },
        { which: undefined, value: 'ỷ' },
        { which: undefined, value: 'ỹ' },
        { which: undefined, value: 'ỵ' },
      ],
    },
    {
      which: 85,
      value: 'u',
      vn: [
        { which: undefined, value: 'ù' },
        { which: undefined, value: 'ú' },
        { which: undefined, value: 'ủ' },
        { which: undefined, value: 'ũ' },
        { which: undefined, value: 'ụ' },
      ],
    },
    {
      which: 73,
      value: 'i',
      vn: [
        { which: 0, value: 'ì' },
        { which: 0, value: 'í' },
        { which: 0, value: 'ỉ' },
        { which: 0, value: 'ĩ' },
        { which: 0, value: 'ị' },
      ],
    },
    {
      which: 79,
      value: 'o',
      vn: [
        { which: undefined, value: 'ò' },
        { which: undefined, value: 'ó' },
        { which: undefined, value: 'ỏ' },
        { which: undefined, value: 'õ' },
        { which: undefined, value: 'ọ' },
        { which: undefined, value: 'ô' },
        { which: undefined, value: 'ồ' },
        { which: undefined, value: 'ố' },
        { which: undefined, value: 'ổ' },
        { which: undefined, value: 'ỗ' },
        { which: undefined, value: 'ộ' },
        { which: undefined, value: 'ơ' },
        { which: undefined, value: 'ờ' },
        { which: undefined, value: 'ớ' },
        { which: undefined, value: 'ở' },
        { which: undefined, value: 'ỡ' },
        { which: undefined, value: 'ợ' },
      ],
    },
    { which: 80, value: 'p' },
  ],
  MIDDLE: [
    {
      which: 65,
      value: 'a',
      vn: [
        { which: undefined, value: 'à' },
        { which: undefined, value: 'á' },
        { which: undefined, value: 'ả' },
        { which: undefined, value: 'ã' },
        { which: undefined, value: 'ạ' },
        { which: undefined, value: 'â' },
        { which: undefined, value: 'ầ' },
        { which: undefined, value: 'ấ' },
        { which: undefined, value: 'ẩ' },
        { which: undefined, value: 'ẫ' },
        { which: undefined, value: 'ậ' },
        { which: undefined, value: 'ă' },
        { which: undefined, value: 'ằ' },
        { which: undefined, value: 'ắ' },
        { which: undefined, value: 'ẳ' },
        { which: undefined, value: 'ẵ' },
        { which: undefined, value: 'ặ' },
      ],
    },
    { which: 83, value: 's' },
    { which: 68, value: 'd', vn: [{ which: undefined, value: 'đ' }] },
    { which: 70, value: 'f' },
    { which: 71, value: 'g' },
    { which: 72, value: 'h' },
    { which: 74, value: 'j' },
    { which: 75, value: 'k' },
    { which: 76, value: 'l' },
  ],
  BOTTOM: [
    { which: 13, value: 'Enter' },
    { which: 90, value: 'z' },
    { which: 88, value: 'x' },
    { which: 67, value: 'c' },
    { which: 86, value: 'v' },
    { which: 66, value: 'b' },
    { which: 78, value: 'n' },
    { which: 77, value: 'm' },
    { which: 8, value: 'Del' },
  ],
};
