export const WORDS_POOL = [
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'cat',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'plant',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'island',
  },
  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'thuỷ',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'pitch',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'perfect',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'chunk',
  },
  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'chống',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'dog',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'baggy',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'goal',
  },
  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'làng',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'drink',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'ignore',
  },

  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'trái',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'kingdom',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'trunk',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'bicycle',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'skill',
  },
  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'kiến',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'original',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'dragon',
  },
  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'sống',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'pleat',
  },
  {
    countryCode: 'us',
    isUnicode: false,
    guessTime: null,
    extraGuessTime: null,
    value: 'death',
  },
  {
    countryCode: 'vn',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'phải',
  },

  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'author',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'artist',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'curve',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'couch',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'enjoyment',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'average',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'complete',
  },

  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'erase',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'famous',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'extreme',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'schedule',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'today',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'weekend',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'favorite',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'moral',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'mystery',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'absent',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'adult',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'sex',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'love',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'arrange',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'chance',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'cubic',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'square',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'oval',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'limit',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'lipid',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'liquid',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'snake',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'tiger',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'monkey',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'buffalo',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'forest',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'mountain',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'double',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'corner',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'quarter',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'divide',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'ghost',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'mineral',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'vitamin',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'human',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'person',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'duck',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'think',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'cancel',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 2,
    value: 'currency',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'brand',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 2,
    value: 'giraffe',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'health',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'commit',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'allow',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: null,
    value: 'adopt',
  },
  {
    countryCode: 'us',
    isUnicode: true,
    guessTime: null,
    extraGuessTime: 3,
    value: 'sophisticate',
  },
];
